version: '3.10'

services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
  web:
    build: ./fabrique
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fabrique/:/code
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    ports:
      - 8000:8000
  celery:
    build: ./fabrique
    command: celery -A fabrique worker -l info
    volumes:
      - ./fabrique/:/code
    depends_on:
      - redis
      - web
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
  flower:
    build: /fabrique
    command: celery -A fabrique flower
    volumes:
      - ./fabrique/:/code
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - celery
      - redis